- packages/global/components/layouts/website-section/home.marko
- packages/global/components/layouts/website-section/marko.json
- sites/ccjdigital.com/server/templates/index.marko
- sites/equipmentworld.com/server/templates/index.marko
- sites/hardworkingtrucks.com/server/templates/index.marko
- sites/overdriveonline.com/server/templates/index.marko
- sites/totallandscapecare.com/server/templates/index.marko
- sites/truckersnews.com/server/templates/index.marko
- sites/truckpartsandservice.com/server/templates/index.marko
> Add google-site-verification meta tags to home pages

- packages/global/routes/feed.js
Render inline images without lazyloading on the content feed.
> Add support for rendering inline images

- sites/truckpartsandservice.com/server/routes/index.js
- sites/truckpartsandservice.com/server/routes/static.js
- sites/truckpartsandservice.com/server/styles/index.scss
- sites/truckpartsandservice.com/server/templates/static/distributor-of-the-year-award.marko
- sites/truckpartsandservice.com/server/templates/static/sucessful-dealer-award.marko
> TPS awards pages

- sites/truckpartsandservice.com/server/templates/static/distributor-of-the-year-award.marko
- sites/truckpartsandservice.com/server/templates/static/sucessful-dealer-award.marko
> Add wrapping body copy containers & classes

- packages/global/scss/components/_ads.scss
> Adjust wallpaper to use fixed positioning

- packages/global/scss/components/_ads.scss
> Position fixed wallpaper at edge of viewport

- packages/equipment-experts/index.js
- sites/equipmentworld.com/server/routes/index.js
Ref #181, fix embedded media renderer.
> Pull parser from the app instance

- packages/global/components/blocks/promos/marko.json
- packages/global/components/blocks/promos/ovd-reader-rigs-submit.marko
- packages/global/utils/shuffle-array.js
- sites/overdriveonline.com/server/components/blocks/marko.json
- sites/overdriveonline.com/server/components/blocks/promo-card-rotation.marko
- sites/overdriveonline.com/server/components/marko.json
- sites/overdriveonline.com/server/templates/content/company.marko
- sites/overdriveonline.com/server/templates/content/index.marko
- sites/overdriveonline.com/server/templates/content/product.marko
- sites/overdriveonline.com/server/templates/index.marko
- sites/overdriveonline.com/server/templates/website-section/index.marko
- sites/overdriveonline.com/server/templates/website-section/partners-in-business.marko
- sites/overdriveonline.com/server/templates/website-section/products.marko
- sites/overdriveonline.com/server/templates/website-section/reader-rigs.marko
> Add promo card rotation support

- sites/equipmentworld.com/server/routes/index.js
- sites/equipmentworld.com/server/routes/static.js
- sites/equipmentworld.com/server/templates/cost-calculator.marko
> Add cost calculator static page

- sites/overdriveonline.com/server/templates/new-reader-rigs-submission.marko
> Clean up reader rigs submission page

- packages/global/components/blocks/latest-products-feed.marko
- packages/global/components/layouts/website-section/products.marko
- packages/global/scss/components/_ads.scss
- packages/global/scss/components/blocks/_latest-products-feed.scss
> Add inline feed ads to products landing page on mobile

- packages/global/package.json
- packages/global/routes/index.js
- packages/global/scss/core.scss
- packages/global/start-server.js
- yarn.lock
> Add marko-web-html-sitemap package

- packages/global/package.json
- sites/ccjdigital.com/config/navigation.js
- sites/equipmentworld.com/config/navigation.js
- sites/hardworkingtrucks.com/config/navigation.js
- sites/overdriveonline.com/config/navigation.js
- sites/totallandscapecare.com/config/navigation.js
- sites/truckersnews.com/config/navigation.js
- sites/truckpartsandservice.com/config/navigation.js
- yarn.lock
> Upgrade sitemap package and add link to footer with new site-map alias

- packages/equipment-experts/index.js
- packages/equipment-experts/package.json
- packages/equipment-experts/renderer.js
Creates an async capable handler for rendering OEmbeds and images within the Equipment Experts project.
When encountering an OEmbed, the renderer will use the BaseCMS OEmbed service to render the result inline, rather than the OEmbed vue component (the default).
Current:
```json
{
"post_content": "\n<p><div id=\"vue-1624635880096-433\"></div><script>CMSBrowserComponents.load({ el: '#vue-1624635880096-433', name: 'OEmbed', props: {\"mountPoint\":\"/__oembed\",\"url\":\"https://www.youtube.com/embed/fmTqRzPYDE8?feature=oembed\",\"attrs\":{\"type\":\"oembed\",\"id\":\"https://www.youtube.com/embed/fmTqRzPYDE8?feature=oembed\",\"element\":\"aside\"}}, hydrate: false });</script></p>\n<p>Work..."
}
```
New:
```json
{
"post_content": "\n<p><iframe class=\"embedly-embed\" …
```
> Inline OEmbed rendering for Equipment Experts API

- packages/global/components/layouts/content/default.marko
- packages/global/components/layouts/content/wrapper.marko
- packages/global/components/nodes/author-published.marko
- packages/global/graphql/fragments/content-page.js
> Addition of author bio for contributors on article

- packages/global/templates/static/one-trust.marko
- sites/ccjdigital.com/config/navigation.js
- sites/equipmentworld.com/config/navigation.js
- sites/hardworkingtrucks.com/config/navigation.js
- sites/overdriveonline.com/config/navigation.js
- sites/totallandscapecare.com/config/navigation.js
- sites/truckersnews.com/config/navigation.js
- sites/truckpartsandservice.com/config/navigation.js
> Correct Terms of Use and Privacy Policy typo

- packages/global/templates/taxonomy.marko
> Add noindex to taxonomy route

- sites/ccjdigital.com/config/top250/index.js
- sites/ccjdigital.com/server/styles/_top-250.scss
- sites/ccjdigital.com/server/templates/website-section/top250/index.marko
> Update title & teaser; hyperlink terms of use

- sites/ccjdigital.com/server/styles/_top-250.scss
> Add sticky header to CCJ Top 250

- sites/ccjdigital.com/config/top250/all.js
- sites/ccjdigital.com/config/top250/index.js
- sites/ccjdigital.com/server/templates/website-section/top250/components/graphic-header.marko
- sites/ccjdigital.com/server/templates/website-section/top250/guide.marko
- sites/ccjdigital.com/server/templates/website-section/top250/index.marko
> Update Top 250 verbiage

- sites/ccjdigital.com/server/styles/_top-250.scss
> Comment out sponsor part of ccj top 250

- packages/equipment-experts/graphql/equipment-experts-content.js
- packages/equipment-experts/index.js
> Return published and last modified on API call hit (Equipment Experts API)

- packages/global/components/blocks/marko.json
- packages/global/components/blocks/primary-image.marko
- packages/global/components/blocks/section-feed.marko
- packages/global/components/blocks/top-stories.marko
- packages/global/components/flows/content/card-deck-4-col.marko
- packages/global/components/layouts/content/default.marko
- packages/global/components/layouts/website-section/feed.marko
- packages/global/components/layouts/website-section/home.marko
- packages/global/components/nodes/author-published.marko
- packages/global/components/nodes/section-feed-content.marko
> Remove lazyload from several above the fold images

- sites/ccjdigital.com/server/routes/content.js
- sites/equipmentworld.com/server/routes/content.js
- sites/hardworkingtrucks.com/server/routes/content.js
- sites/overdriveonline.com/server/routes/content.js
- sites/totallandscapecare.com/server/routes/content.js
- sites/truckersnews.com/server/routes/content.js
- sites/truckpartsandservice.com/server/routes/content.js
> Update content route regex

- sites/ccjdigital.com/server/templates/content/company.marko
- sites/equipmentworld.com/server/templates/content/company.marko
- sites/hardworkingtrucks.com/server/templates/content/company.marko
- sites/overdriveonline.com/server/templates/content/company.marko
- sites/totallandscapecare.com/server/templates/content/company.marko
- sites/truckersnews.com/server/templates/content/company.marko
> Increase company page article limits from 3 to 15.

- packages/global/components/blocks/ccj-solutions-summit.marko
- packages/global/components/blocks/ccj-top-250.marko
- packages/global/components/blocks/eqw-coty-promo.marko
- packages/global/components/blocks/marko.json
- packages/global/components/blocks/successful-dealer-sponsors.marko
- packages/global/scss/components/blocks/_ccj-solutions-summit.scss
- packages/global/scss/core.scss
- sites/ccjdigital.com/server/templates/content/company.marko
- sites/ccjdigital.com/server/templates/content/index.marko
- sites/ccjdigital.com/server/templates/content/product.marko
- sites/ccjdigital.com/server/templates/index.marko
- sites/ccjdigital.com/server/templates/website-section/index.marko
- sites/ccjdigital.com/server/templates/website-section/products.marko
> Add CCJ Solutions Summit promotional block

- packages/global/components/blocks/successful-dealer-sponsors.marko
> Replace Top Mark with Automann. TPS Successful Dealer Awards page.

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Change deadline date to November 26, 2021. COTY Page EQW.

- sites/ccjdigital.com/server/templates/content/company.marko
- sites/ccjdigital.com/server/templates/content/index.marko
- sites/ccjdigital.com/server/templates/content/product.marko
- sites/ccjdigital.com/server/templates/index.marko
- sites/ccjdigital.com/server/templates/website-section/index.marko
- sites/ccjdigital.com/server/templates/website-section/products.marko
> Change Solution Summit promo back to Top 250 promo

- sites/overdriveonline.com/server/templates/website-section/partners-in-business.marko
> Remove sponsored description from ‘partners-in-business’ block

- packages/global/components/layouts/content/default.marko
- packages/theme-monorail/components/identity-x/content-page-gate.marko
- packages/theme-monorail/components/identity-x/marko.json
- packages/theme-monorail/graphql/fragments/content-page.js
- packages/theme-monorail/scss/components/_content-page.scss
- packages/theme-monorail/utils/get-content-preview.js
Requires https://github.com/parameter1/base-cms/pull/231 to be merged & deployed
> Add content gating to monorail and global packages

- sites/ccjdigital.com/config/site.js
- sites/equipmentworld.com/config/site.js
- sites/hardworkingtrucks.com/config/site.js
- sites/overdriveonline.com/config/site.js
- sites/totallandscapecare.com/config/site.js
- sites/truckpartsandservice.com/config/site.js
> Update all site logos (except Truckers News)

- packages/global/components/blocks/ovd-pib-manual-promo.marko
> Changeover image, year + access link for OVD PIB 2022.

- packages/global/components/layouts/website-section/feed.marko
- sites/truckpartsandservice.com/config/navigation.js
- sites/truckpartsandservice.com/server/routes/index.js
- sites/truckpartsandservice.com/server/routes/static.js
- sites/truckpartsandservice.com/server/templates/static/distributor-of-the-year-award.marko
- sites/truckpartsandservice.com/server/templates/static/successful-dealer-award-nomination.marko
Nomination Pages:
Archive Pages:
> TPS Award Nomination and Award Archive pages.

- packages/global/config/identity-x.js
- packages/global/scss/components/user.scss
Make the form be max width of 400px and align centered
> Update /user pages styling

- packages/global/components/document.marko
Test adding the deferred loading of the reCAPTCHA script on RR before update base-cms package
> Switch reCAPTCHA v3 script inclusion to on load

- sites/equipmentworld.com/server/components/coty-nav.marko
- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Adjust page copy for Contractor of the Year landing page.

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Correct query string on srcset url, COTY landing page.

- packages/dun-and-bradstreet-lambda/aws.js
- packages/dun-and-bradstreet-lambda/env.js
- packages/dun-and-bradstreet-lambda/functions/enqueue.js
- packages/dun-and-bradstreet-lambda/functions/process.js
- packages/dun-and-bradstreet-lambda/functions/stream-from-queue.js
- packages/dun-and-bradstreet-lambda/package.json
- packages/global/browser/dun-and-bradstreet.js
- packages/global/browser/index.js
- scripts/build-lambdas.js
- yarn.lock
On window load, retrieve the D&B image pixel, script, and invoke the `getData` method. Once called, the response will be sent to AWS for processing.
> Create Dun & Bradstreet lambda functions and client-side tracking

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Update ‘Download Paper Application’ pdf/button

- packages/global/scss/core.scss
> Update embedded image styling

- packages/global/components/layouts/content/default.marko
> Add partner-insights native-x position to related stories block

- packages/global/browser/dun-and-bradstreet.js
Also, remove `jobFunction` as a required field
> Handle D&B field state history and resync when necessary

- packages/global/components/blocks/sponsors.marko
> Add Karmak to Successful Dealer Award Sponsors

- packages/global/components/document.marko
- packages/global/package.json
- yarn.lock
> Upgrade p1-events package version & ensure brandKey & identityQueryBuilder function are set correctly.

- sites/ccjdigital.com/config/top250/_csv/top250.csv
> Allow for --'s for Not Ranked (NR) 2021 Rank col, CCJ Top 250

- sites/equipmentworld.com/config/gam.js
- sites/totallandscapecare.com/config/gam.js
Configuration copied from https://github.com/parameter1/randall-reilly-websites/blob/master/sites/ccjdigital.com/config/gam.js
> Disable GAM lazyloading on TLC and EQW

- sites/ccjdigital.com/config/top250/_csv/top250.csv
Confirmed this removes the duplicates that would be found on https://www.ccjdigital.com/ccj-top-250/all (Difficult to take a screenshot given I believe this is only an issue in this pages select box)
> Correct data irregularity in Primary Operation(s)

- sites/ccjdigital.com/config/top250/index.js
> Add download link for Top 250 PDF with verbiage.

- sites/ccjdigital.com/config/top250/_csv/top250.csv
> "Null out" Tri-National''s 2021 Revenue, CCJ Top 250

- sites/ccjdigital.com/config/identity-x.js
- sites/ccjdigital.com/index.js
- sites/equipmentworld.com/index.js
- sites/totallandscapecare.com/index.js
Enable content gating and remove site specific serverRequiredFields
> Setup content metering for CCJ

- sites/ccjdigital.com/config/top250/_csv/top250.csv
> Blank out Tri-National's Carriers field CCJ Top 250

- packages/global/middleware/newsletter-state.js
- sites/ccjdigital.com/server/routes/content.js
- sites/equipmentworld.com/server/routes/content.js
- sites/hardworkingtrucks.com/server/routes/content.js
- sites/overdriveonline.com/server/routes/content.js
- sites/totallandscapecare.com/server/routes/content.js
- sites/truckersnews.com/server/routes/content.js
This will trigger the newsletter pushdown
> add formateResponse to content route

- packages/global/components/blocks/content-meter.marko
> Adjust verbiage when limit is reached for a viewable article

- sites/truckpartsandservice.com/config/gam.js
> Add marginPercent to lazyloading

- packages/global/components/layouts/content/default.marko
- packages/global/components/layouts/content/product.marko
- packages/global/components/layouts/website-section/feed.marko
- packages/global/components/layouts/website-section/home.marko
- packages/global/components/layouts/website-section/products.marko
- packages/global/config/gam.js
- packages/global/package.json
- packages/global/scss/core.scss
- sites/ccjdigital.com/config/gam.js
- sites/equipmentworld.com/config/gam.js
- sites/hardworkingtrucks.com/config/gam.js
- sites/overdriveonline.com/config/gam.js
- sites/totallandscapecare.com/config/gam.js
- sites/truckersnews.com/config/gam.js
- sites/truckpartsandservice.com/config/gam.js
- yarn.lock
Reverts parameter1/randall-reilly-websites#473
> Revert "Move leaderboard below the fold on mobile for OVD, CCJ"

- packages/global/components/layouts/content/default.marko
- packages/global/components/layouts/content/product.marko
- packages/global/components/layouts/website-section/feed.marko
- packages/global/components/layouts/website-section/home.marko
- packages/global/components/layouts/website-section/products.marko
- packages/global/config/gam.js
- packages/global/package.json
- packages/global/scss/core.scss
- sites/ccjdigital.com/config/gam.js
- sites/equipmentworld.com/config/gam.js
- sites/hardworkingtrucks.com/config/gam.js
- sites/overdriveonline.com/config/gam.js
- sites/totallandscapecare.com/config/gam.js
- sites/truckersnews.com/config/gam.js
- sites/truckpartsandservice.com/config/gam.js
- yarn.lock
Reverts parameter1/randall-reilly-websites#474
> Move leaderboard below the fold on mobile for OVD, CCJ

- sites/truckpartsandservice.com/config/navigation.js
> Add whitepapers to menu

- packages/global/package.json
- sites/ccjdigital.com/package.json
- sites/equipmentworld.com/package.json
- sites/hardworkingtrucks.com/package.json
- sites/overdriveonline.com/package.json
- sites/totallandscapecare.com/package.json
- sites/truckersnews.com/package.json
- sites/truckpartsandservice.com/package.json
- yarn.lock
> Upgrade dependencies

- sites/ccjdigital.com/config/site.js
Missed this with the original change
> Update CCJ's oneTrust site config.

- packages/global/middleware/content-meter.js
> Add ability to bypass content meter w/query param

- sites/ccjdigital.com/config/navigation.js
- sites/equipmentworld.com/config/navigation.js
- sites/hardworkingtrucks.com/config/navigation.js
- sites/overdriveonline.com/config/navigation.js
- sites/totallandscapecare.com/config/navigation.js
- sites/truckersnews.com/config/navigation.js
- sites/truckpartsandservice.com/config/navigation.js
> Remove Point of Collection, alter Personal Information verbiage in footer navigations

- sites/totallandscapecare.com/config/navigation.js
- sites/totallandscapecare.com/config/one-trust.js
> Add ‘Cookie Settings’ to footer

- sites/truckpartsandservice.com/config/navigation.js
> Add ‘Trailblazer Award’ to hamburger menu

- packages/global/components/layouts/content/company.marko
- packages/global/components/layouts/content/default.marko
- packages/global/components/layouts/content/product.marko
- packages/global/components/layouts/website-section/feed.marko
- packages/global/components/layouts/website-section/home.marko
- packages/global/components/layouts/website-section/products.marko
- packages/global/templates/content/contact.marko
- sites/equipmentworld.com/server/templates/website-section/safety-watch.marko
> Correctly look for both Pinned and Standard option schedules for total count

- packages/global/browser/index.js
Upgrade @parameter1/base-cms deps once https://github.com/parameter1/base-cms/pull/687 is merged and release will make this a duplicate push to the datalayer
> Use upgraded identityX package with built in emitter

- packages/global/scss/_variables.scss
Add fallback fonts for primary and secondary fonts
> Add font fallbacks for primary and secondary fonts

- packages/global/scss/core.scss
> Add resource-library component in homepage critical CSS

- sites/ccjdigital.com/config/gam.js
> Update CCJ mobile Leaderboard path `gear-leaderboard` to `leaderboard`

- packages/global/package.json
- packages/global/scss/core.scss
- sites/ccjdigital.com/config/newsletter.js
- sites/ccjdigital.com/package.json
- sites/equipmentworld.com/config/newsletter.js
- sites/equipmentworld.com/package.json
- sites/hardworkingtrucks.com/config/newsletter.js
- sites/hardworkingtrucks.com/package.json
- sites/overdriveonline.com/config/newsletter.js
- sites/overdriveonline.com/package.json
- sites/totallandscapecare.com/config/newsletter.js
- sites/totallandscapecare.com/package.json
- sites/truckersnews.com/config/newsletter.js
- sites/truckersnews.com/package.json
- sites/truckpartsandservice.com/config/newsletter.js
- sites/truckpartsandservice.com/package.json
- yarn.lock
Requires: https://github.com/parameter1/base-cms/pull/734 merged/tagged/released  & a deps to be upgraded.
@todo determine if there is a max width that needs to be applied to the form in step1 or if the fill available space is okay.
> Adjust newsletter pushdown

- packages/global/package.json
- sites/ccjdigital.com/package.json
- sites/equipmentworld.com/package.json
- sites/hardworkingtrucks.com/package.json
- sites/overdriveonline.com/package.json
- sites/totallandscapecare.com/package.json
- sites/truckersnews.com/package.json
- sites/truckpartsandservice.com/package.json
- yarn.lock
Fixes the newsletter toggle/close button when initially expanded.
> @parameter1/base-cms depUpgrades V4.30.1

- sites/equipmentworld.com/server/components/coty-nav.marko
- sites/equipmentworld.com/server/styles/index.scss
- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
Screenshots showing Desktop and Mobile (iPhone SE):
> Equipment World Contractor of the Year 2024 Page Update

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Swap Contractor of the Year buttons to Notification button

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Swap back to Apply and Form buttons, change Paper app URL. EQW Contractor of the Year

- packages/global/components/layouts/content/company-details/company-logo.marko
- packages/global/components/layouts/content/company-details/leaders-details.marko
- packages/global/components/layouts/content/company-details/marko.json
- packages/global/components/layouts/content/marko.json
- sites/truckpartsandservice.com/browser/index.js
- sites/truckpartsandservice.com/package.json
- sites/truckpartsandservice.com/server/graphql/company-page-fragment.js
- sites/truckpartsandservice.com/server/routes/content.js
- sites/truckpartsandservice.com/server/styles/_company-page.scss
- sites/truckpartsandservice.com/server/styles/_leaders.scss
- sites/truckpartsandservice.com/server/styles/index.scss
- sites/truckpartsandservice.com/server/templates/content/company.marko
- yarn.lock
EDIT: Approved by the Randall-Reilly team in it's current state
> Update TPS Company Page Layout

- packages/global/components/blocks/stories.marko
- packages/global/scss/components/blocks/_inbody-related-stories.scss
> update in body stories block and css

- packages/rigdig/browser/checkout-header.vue
- packages/rigdig/browser/checkout-modal.vue
- sites/overdriveonline.com/server/styles/components/_rigdig.scss
Rework UI to align with updated figma presentation for two-step checkout
| Step 2 | Step 1, authed | Step 1, Unauthed |
| - | - | - |
|  ![image](https://github.com/parameter1/randall-reilly-websites/assets/1778222/12243408-c7d1-4d48-8ec6-38b841b03219) | ![image](https://github.com/parameter1/randall-reilly-websites/assets/1778222/4da3148b-1891-4485-b628-eef594665a04) | ![image](https://github.com/parameter1/randall-reilly-websites/assets/1778222/638f0db2-8a42-4a01-9b99-1d604298196b) |
> RigDig ui/x updates

- packages/global/components/layouts/content/default.marko
- packages/global/scss/core.scss
> Adjust content page gate css

- sites/overdriveonline.com/config/site.js
> Replace Stitcher podcast link with Google Podcasts, OVD

- packages/global/scss/core.scss
> Minor adjustments to inBody newsletter signup box

- packages/rigdig/browser/widget.vue
- packages/rigdig/components/widget.marko
- packages/rigdig/scss/rigdig.scss
- sites/truckhistoryreport.com/config/site.js
- sites/truckhistoryreport.com/server/components/blocks/questions.marko
- sites/truckhistoryreport.com/server/styles/index.scss
- sites/truckhistoryreport.com/server/templates/index.marko
@todo account for all the mobile nuances
> Widen Truck History Report  and adjust styles to better match design.

- packages/rigdig/src/templates/notification.marko
@todo apply font families.  At the moment we update the template & am looking into additional font family changes.
> Update notification template

- packages/rigdig/scss/rigdig.scss
- sites/truckhistoryreport.com/server/styles/index.scss
- sites/truckhistoryreport.com/server/templates/index.marko
<p>
<b>Desktop</b>
<br>
</p>
<p>
<b>Mobile</b><br>
</p>
<p>
<b>Reset Button</b><br>
</p>
> Update THR's intro block style & reset button alignment

- packages/rigdig/browser/checkout-modal.vue
- packages/rigdig/scss/rigdig.scss
- packages/rigdig/src/index.js
- sites/truckhistoryreport.com/server/templates/index.marko
> Update step 3 payment received modal info/layout

- sites/cleantrucking.com/config/newsletter.js
> Set CT newsletter titles and descriptions

- packages/rigdig/browser/checkout-modal.vue
> Update error message location reference

- packages/rigdig/browser/checkout-modal.vue
> Update invalid email address error

- packages/rigdig/browser/checkout-modal.vue
- packages/rigdig/browser/index.js
- packages/rigdig/browser/widget.vue
> Add component events and push to dataLayer

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Set deadline to October 6, 2023, EQW COTY

- sites/cleantrucking.com/config/site.js
> Use new svg logo

- packages/rigdig/src/templates/notification.marko
correctly get properties off of the report to prevent erring when report is undefined.
> Prevent rig dig notification prop destructure error.

- packages/rigdig/browser/widget.vue
> Remove THR widget's onPasteHandler for submit

- sites/truckhistoryreport.com/server/templates/index.marko
> Add google site verification for THR

- sites/cleantrucking.com/config/identity-x-opt-in-hooks.js
- sites/cleantrucking.com/config/navigation.js
- sites/cleantrucking.com/config/newsletter.js
They said deploymentTypeId 172, which is the altId
> Update newsletter signup configuration and pushdown.

- sites/cleantrucking.com/config/navigation.js
> Move Maintenace from nav to menu, Clean Trucking

- sites/cleantrucking.com/config/navigation.js
- sites/cleantrucking.com/config/site.js
- sites/cleantrucking.com/server/styles/index.scss
> Update nav, social icons, & footer logo

- sites/truckhistoryreport.com/server/templates/index.marko
> Remove access past reports link, THR promo block

- sites/cleantrucking.com/config/navigation.js
- sites/cleantrucking.com/server/templates/index.marko
> Add regulation & legislation to dropdown menu & update Videos description

- packages/global/components/layouts/content/company.marko
- packages/overdrive/config/search.js
- sites/ccjdigital.com/config/search.js
- sites/ccjdigital.com/config/site.js
- sites/equipmentworld.com/config/search.js
- sites/equipmentworld.com/config/site.js
- sites/hardworkingtrucks.com/config/search.js
- sites/hardworkingtrucks.com/config/site.js
- sites/totallandscapecare.com/config/search.js
- sites/totallandscapecare.com/config/site.js
- sites/truckersnews.com/config/search.js
- sites/truckersnews.com/config/site.js
- sites/truckpartsandservice.com/config/search.js
- sites/truckpartsandservice.com/config/site.js
Replaces: https://github.com/parameter1/randall-reilly-websites/pull/554
(Inquiry is currently disabled for all sites but figure this is worth correcting in the event it ever does get enabled):
Search Page:
> Inquiry and search configuration alterations

- docker-compose.yml
- packages/rigdig/src/client.js
- packages/rigdig/src/index.js
- packages/rigdig/src/send-error-notification.js
- packages/rigdig/src/send-notification.js
Adds additional logging for SendGrid delivery, catch email notification errors, and force re-authenticating when encountering a 401 (expired token).
> Update THR error handling

- sites/ccjdigital.com/config/i18n.js
- sites/ccjdigital.com/index.js
- sites/cleantrucking.com/config/i18n.js
- sites/cleantrucking.com/index.js
- sites/equipmentworld.com/config/i18n.js
- sites/equipmentworld.com/index.js
- sites/hardworkingtrucks.com/config/i18n.js
- sites/hardworkingtrucks.com/index.js
- sites/overdriveonline.com/config/i18n.js
- sites/overdriveonline.com/index.js
- sites/totallandscapecare.com/config/i18n.js
- sites/totallandscapecare.com/index.js
- sites/truckersnews.com/config/i18n.js
- sites/truckersnews.com/index.js
- sites/truckpartsandservice.com/config/i18n.js
- sites/truckpartsandservice.com/index.js
> Rename `Sponsor Content` to `Featured Sponsor`, utilize i18n

- packages/global/components/blocks/partner-insights-promo.marko
Missed fixing the spelling here.
> Fix spelling of Partner Insights

- packages/global/components/blocks/partner-insights-promo.marko
> remove view all and update CTA of Partner Insights

- packages/payfabric/src/utils/pre-tax-amount.js
- packages/rigdig/browser/checkout-header.vue
- packages/rigdig/browser/checkout-modal.vue
> Sales tax calculation and display corrections

- packages/global/components/blocks/sponsors.marko
> Increase set height to 200 for sponsors logos

- sites/ccjdigital.com/server/components/blocks/promo-card-rotation.marko
- sites/ccjdigital.com/server/templates/index.marko
- sites/equipmentworld.com/server/components/blocks/promo-card-rotation.marko
- sites/equipmentworld.com/server/templates/index.marko
- sites/overdriveonline.com/server/components/blocks/promo-card-rotation.marko
- sites/overdriveonline.com/server/templates/index.marko
- sites/totallandscapecare.com/server/components/blocks/promo-card-rotation.marko
- sites/totallandscapecare.com/server/templates/index.marko
- sites/truckpartsandservice.com/server/components/blocks/promo-card-rotation.marko
- sites/truckpartsandservice.com/server/templates/index.marko
Make it always rotate within the promo cards
> Remove env based Partner Insight block logic & enable within production

- packages/global/components/blocks/marko.json
- packages/global/components/blocks/sponsors.marko
- sites/truckpartsandservice.com/server/routes/static.js
- sites/truckpartsandservice.com/server/templates/static/distributor-of-the-year-award.marko
> Distributor of the Year Landing Page, TPS

- packages/overdrive/config/site.js
- sites/ccjdigital.com/config/site.js
- sites/cleantrucking.com/config/site.js
- sites/equipmentworld.com/config/site.js
- sites/hardworkingtrucks.com/config/site.js
- sites/totallandscapecare.com/config/site.js
- sites/truckersnews.com/config/site.js
- sites/truckpartsandservice.com/config/site.js
> Replace all the applicable logos

- sites/truckersnews.com/config/site.js
> Revert change to TN randall reilly logo in footer

- sites/totallandscapecare.com/server/styles/index.scss
- sites/truckpartsandservice.com/server/styles/index.scss
> Increase footer site logo for TPS and TLC

- packages/global/middleware/content-meter.js
Add the checking of content gating to the content metering middleware
@todo - investigate what it would take to make this use monorail version of middleware.
> Add content gating check to prevent  the contentMeter & hardGate from firing together

- packages/overdrive/config/navigation.js
- packages/overdrive/config/site.js
- sites/ccjdigital.com/config/navigation.js
- sites/ccjdigital.com/config/site.js
- sites/cleantrucking.com/config/navigation.js
- sites/cleantrucking.com/config/site.js
- sites/equipmentworld.com/config/navigation.js
- sites/equipmentworld.com/config/site.js
- sites/hardworkingtrucks.com/config/navigation.js
- sites/hardworkingtrucks.com/config/site.js
- sites/totallandscapecare.com/config/navigation.js
- sites/totallandscapecare.com/config/site.js
- sites/truckersnews.com/config/site.js
- sites/truckhistoryreport.com/config/navigation.js
- sites/truckpartsandservice.com/config/navigation.js
- sites/truckpartsandservice.com/config/site.js
> Update do not sell link, terms and privacy pages

- sites/truckpartsandservice.com/server/templates/static/distributor-of-the-year-award.marko
> TPS DOTY 2024 information updates

- packages/global/components/blocks/ovd-pib-manual-promo.marko
> Update OVD PIB image

- packages/global/routes/native-x.js
- packages/global/templates/partner-insights.marko
- packages/overdrive/config/native-x.js
- sites/ccjdigital.com/config/native-x.js
- sites/cleantrucking.com/config/native-x.js
- sites/equipmentworld.com/config/native-x.js
- sites/hardworkingtrucks.com/config/native-x.js
- sites/totallandscapecare.com/config/native-x.js
- sites/truckersnews.com/config/native-x.js
- sites/truckpartsandservice.com/config/native-x.js
> Partner Insights Pages

- packages/global/components/blocks/ovd-pib-manual-promo.marko
> Update pib promo

- packages/global/templates/partner-insights.marko
> Include Whitepapers and remove inline GAM ads on Partner Insights pages

- packages/global/components/blocks/eqw-coty-promo.marko
- sites/equipmentworld.com/server/components/coty-nav.marko
- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Contractor of the Year 2024

- packages/global/config/gam.js
RR understands the ad it larger than viewport and confirms
> Add 430x720 ad size to viewport [300, 0]

- packages/global/components/layouts/content/default.marko
> Enforce 4 columns on injected Native-X Card Deck

- sites/equipmentworld.com/config/navigation.js
> Add Compact Wheel Loaders section to menu

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Update Contractor of the Year page

- packages/overdrive/config/site.js
> Swap out Google Podcasts with Youtube link for OVD Podcast block

- sites/ccjdigital.com/server/public/robots.txt
- sites/cleantrucking.com/server/public/robots.txt
- sites/equipmentworld.com/server/public/robots.txt
- sites/hardworkingtrucks.com/server/public/robots.txt
- sites/overdriveonline.com/server/public/robots.txt
- sites/totallandscapecare.com/server/public/robots.txt
- sites/truckersnews.com/server/public/robots.txt
- sites/truckpartsandservice.com/server/public/robots.txt
> Add OAI-Searchbot disallow to robots.txt

- sites/truckpartsandservice.com/config/navigation.js
> Update ‘trailblazer award’ url

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Update COTY page

- packages/rigdig/browser/widget.vue
- sites/truckhistoryreport.com/server/templates/index.marko
> Image and information adjustments, Truck History Report

- sites/ccjdigital.com/config/top250/_csv/top250.csv
- sites/ccjdigital.com/server/templates/website-section/top250/guide.marko
- sites/ccjdigital.com/server/templates/website-section/top250/index.marko
> Correct data and call to action copy for CCJ Top 250

- sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
> Update deadline date - COTY

- sites/cleantrucking.com/server/styles/index.scss
Tablet (don't think this will be a point of concern:
> Decrease font size to fit all topics in nav

- sites/cleantrucking.com/server/styles/index.scss
> Increase font size and reduce padding in nav

- packages/global/components/layouts/website-section/feed.marko
PRODUCTION:
DEVELOPMENT:
Showing other sections are not impacted:
> Don't place Sponsor Content on CCJ Innovators section page

- packages/global/browser/load-analyzer.vue
- packages/global/scss/components/load-analyzer.scss
> Add wrapper & styling for $ to appear as leading character in input

- packages/global/browser/load-analyzer.vue
> Fix the payload being send to dataLayer.

- sites/truckersnews.com/config/navigation.js
- sites/truckersnews.com/config/privacy-policy.js
- sites/truckersnews.com/config/site.js
> Update footer--Truckers News

- packages/global/components/blocks/job-search.marko
on submit it will generate https://www.careersingear.com/search?keywords=&location=&utm_source=TruckersNews&utm_medium=jobs&utm_campaign=search
> update campaign value to search

- packages/overdrive/config/navigation.js
- sites/ccjdigital.com/config/navigation.js
- sites/equipmentworld.com/config/navigation.js
- sites/truckpartsandservice.com/config/navigation.js
> Adjustments to navigations for CCJ, OVD, TPS and EQW

- sites/ccjdigital.com/config/navigation.js
> Move Alt Power to menu, replace on nav with Regulations, CCJ

- packages/global/components/blocks/load-analyzer-inbody-promo.marko
- packages/global/scss/components/blocks/_load-analyzer-inbody.scss
Production ref: https://github.com/parameter1/randall-reilly-websites/pull/793
> Staging in body

- packages/global/components/blocks/load-analyzer-inbody-promo.marko
- packages/overdrive/config/navigation.js
Production refs: https://github.com/parameter1/randall-reilly-websites/pull/793
> Staging:  Adjustments to load-analyzer inbody ad

- packages/global/package.json
- packages/global/routes/native-x.js
- packages/global/start-server.js
- packages/global/templates/content/advertising-post.marko
- packages/overdrive/config/site.js
- sites/ccjdigital.com/config/site.js
- sites/cleantrucking.com/config/site.js
- sites/equipmentworld.com/config/site.js
- sites/hardworkingtrucks.com/config/site.js
- sites/totallandscapecare.com/config/site.js
- sites/truckersnews.com/config/site.js
- sites/truckpartsandservice.com/config/site.js
- yarn.lock
>  Upgrade Mindful Post routing middleware to shared base-cms package

- packages/global/templates/content/advertising-post.marko
> Render the advertise name correctly in related story section.

- packages/global/components/blocks/ovd-pride-polish-promo.marko
- sites/overdriveonline.com/server/components/blocks/promo-card-rotation.marko
> Pride polish promo card, OVD

- packages/global/components/blocks/load-analyzer-inbody-promo.marko
> Remove section link

- packages/global/components/blocks/sponsors.marko
> Update sponsors on Distibutor of the Year & Sussessful Dealer Award
