parameter1/fusable-websites

packages/global/browser/index.js, packages/global/components/blocks/primary-image.marko, packages/global/graphql/fragments/native-x-image.js, packages/global/graphql/fragments/native-x-story.js, packages/global/package.json, packages/global/routes/index.js, packages/global/routes/native-x.js, packages/global/scss/components/_page-wrapper.scss, packages/global/scss/components/_sponsor-logo.scss, packages/global/templates/content/components/presented-by.marko, packages/global/templates/content/native-x-story.marko, yarn.lock
Utilizes new middleware from parameter1/base-cms#60 to retrieve a story and render it on the site.
=> Serve NativeX stories

packages/global/start-server.js
```
{
Days: 7
IncludeContentTypes: [‘Article’]
ExcludeLabels: [‘Sponsored’, ‘Sponsored by RoadPro’]
}
```
Will require this service update to be merged and deployed prior to it working https://github.com/parameter1/base-cms/pull/97
=> Update Google News Header params

packages/global/browser/newsletter-signup-form/privacy-policy.vue, packages/global/scss/components/_site-newsletter-menu.scss
Per [Google](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed), this hides the ReCaptcha badge that is placed on all pages and instead puts the privacy policy and terms within the newsletter form
=> Hide recaptcha badge but add policy to user-flow

packages/global/components/layouts/content/default.marko, packages/global/graphql/fragments/content-page.js, packages/global/scss/components/_author-published-node.scss
Also removes “strange” author/contact display logic, since contributors and photographers are never displayed. Also removes webinar and event logic since these content types are currently unused. This can be revisited if/when those content types are brought into use.
This fixes a the "floating headshot" problem where an author missing a bio simply had an image and a name.
It also resolves spacing between the bio section and the newsletter signup form.
New:
Old "headshot" and spacing problem:
=> Only show author bios at the end of content bodies

packages/global/browser/inline-newsletter-form.vue, packages/global/browser/inline-newsletter-form/step1.vue, packages/global/browser/newsletter-signup-form/privacy-policy.vue, packages/global/browser/newsletter-signup-form/sign-up-button.vue, packages/global/browser/newsletter-signup-form/step2.vue, packages/global/browser/site-newsletter-menu.vue, packages/global/components/blocks/newsletter-signup-banner.marko, packages/global/components/site-newsletter-menu.marko, packages/global/scss/components/_site-newsletter-menu.scss, sites/ccjdigital.com/config/newsletter.js, sites/equipmentworld.com/config/newsletter.js, sites/hardworkingtrucks.com/config/newsletter.js, sites/overdriveonline.com/config/newsletter.js, sites/totallandscapecare.com/config/newsletter.js, sites/truckersnews.com/config/newsletter.js, sites/truckpartsandservice.com/config/newsletter.js
- remove `max-width` properties from privacy policy containers
- add privacy policy (and recaptcha) language to step one of the inline form
- adjust step two thank you message to read "Thank you for subscribing" with a body of `You should start receiving your subscription in the next 24 hours along with a special welcome from the experts at <em>{{ siteName }}</em>`
- use full-size newsletter "phone images" on inline form (due to increased size of the privacy language)
- change `Terms & Conditions` to `Terms of Use` in privacy language
=> Newsletter sign-up form adjustments

packages/global/browser/index.js, packages/global/browser/inline-newsletter-form.vue, packages/global/browser/inline-newsletter-form/step1.vue, packages/global/browser/newsletter-signup-form/newsletter-checkbox.vue, packages/global/browser/newsletter-signup-form/step2.vue, packages/global/browser/site-newsletter-menu.vue, packages/global/browser/site-newsletter-menu/step1.vue, packages/global/components/document.marko, sites/ccjdigital.com/config/newsletter.js, sites/equipmentworld.com/config/newsletter.js, sites/hardworkingtrucks.com/config/newsletter.js, sites/overdriveonline.com/config/newsletter.js, sites/totallandscapecare.com/config/newsletter.js, sites/truckersnews.com/config/newsletter.js, sites/truckpartsandservice.com/config/newsletter.js
Newsletters that were specifically subscribed will be emitted to GTM via the `newsletter-form-subscription` event with the following signature: 
```js
{
category: 'Daily Newsletter Subscription', // the newsletter category, as defined in the site's newsletter config
action: 'Pushdown', // either Pushdown or Inline
}
```
=> Emit newsletter subscription events to GTM

sites/truckpartsandservice.com/server/routes/index.js
This goes alongside redirects that redirects from these aliases to the non-nomination versions of these pages /distributor-of-the-year and /successful-dealer-award
=> Temporarily hide the nominations pages for awards.

sites/ccjdigital.com/server/routes/top250.js, sites/ccjdigital.com/server/templates/website-section/top250/guide.marko, sites/ccjdigital.com/server/templates/website-section/top250/index.marko
Update CCJ top 250 guide routes to use the global website section default layout and root(ccj-top-250) website section context.
All guides and the section landing page should use the related section context for ccj top 250.  So on ccj-top-250/all it should still load the site section context for ccj-top-250 section, but display the guide/chart for all operations.
=> Convert CCJ top 250 landing and guide pages to use website-section page type and context base off root ccj-top-250 section

packages/global/scss/components/_content-page.scss
These changes will make the node-list with section-feed nodes have the same look & functionality, but with minor image and title size adjustments.
The ordered and unorderd list will now have the standard list position instead of inside it was picking up from the mixin css
=> Add nodelist sectionfeed css & ol/ul style position change

packages/global/middleware/post-id-handler.js, sites/ccjdigital.com/server/routes/home.js, sites/equipmentworld.com/server/routes/home.js, sites/hardworkingtrucks.com/server/routes/home.js, sites/overdriveonline.com/server/routes/home.js, sites/totallandscapecare.com/server/routes/home.js, sites/truckersnews.com/server/routes/home.js, sites/truckpartsandservice.com/server/routes/home.js
This will require a dependency upgrade following the merge of https://github.com/parameter1/base-cms/pull/202
EDIT: Scratch the dep upgrade, forgot the GraphQL server is completely separate from anything in the sites.
=> Create custom redirect middleware to handle /?p={WORDPRESS_POST_ID} on homepages.

sites/overdriveonline.com/config/site.js, sites/overdriveonline.com/server/templates/website-section/partners-in-business.marko
=> Remove ‘TBS’ logo from ‘partners in business’

packages/global/components/blocks/related-stories.marko
=> Exclude specific content types from Related Stories block "backfill"

packages/theme-monorail/scss/_variables.scss
This includes RR logo & all brand logos
=> Increase all logo heights to 65px

packages/theme-monorail/scss/_variables.scss
=> Revert navbar logo height back to original

packages/global/components/blocks/content-meter.marko, packages/global/components/document.marko, packages/global/middleware/content-meter.js, packages/global/scss/components/content-meter.scss
Update check to enabled, not logged in & oyl_enc_id is set or logged in and all required fields are met.
update verbiage to show  if one view remains `You have 1 article view remaining.` or `You have ${viewLimit - views} article views remaining.`
Also add min height css on login form wrapper to prevent the bar height from changing while waiting on the idX login form to render.
=> Update to Content Meter: When to displays ||  Verbiage on remaining views || CLS on initial display of bar

sites/overdriveonline.com/server/templates/website-section/partners-in-business.marko
=> Prevent shuffle of promos on PIB section page, Overdrive.

sites/truckpartsandservice.com/server/templates/index.marko, sites/truckpartsandservice.com/server/templates/static/successful-dealer-award-nomination.marko
=> Correct homepage alias for distributor-of-the-year-archive and changeout SDA logo.

packages/global/components/blocks/content-meter.marko, packages/global/scss/components/content-meter.scss
=> Add ability to add style to the site name in content meter bar

packages/global/components/layouts/content/default.marko, packages/global/middleware/newsletter-state.js, packages/global/start-server.js, packages/theme-monorail/components/site-newsletter-menu.marko, sites/ccjdigital.com/server/routes/content.js, sites/ccjdigital.com/server/routes/home.js, sites/ccjdigital.com/server/routes/website-section.js, sites/equipmentworld.com/server/routes/content.js, sites/equipmentworld.com/server/routes/home.js, sites/equipmentworld.com/server/routes/website-section.js, sites/hardworkingtrucks.com/server/routes/content.js, sites/hardworkingtrucks.com/server/routes/home.js, sites/overdriveonline.com/server/routes/content.js, sites/overdriveonline.com/server/routes/home.js, sites/overdriveonline.com/server/routes/website-section.js, sites/totallandscapecare.com/server/routes/content.js, sites/totallandscapecare.com/server/routes/home.js, sites/totallandscapecare.com/server/routes/website-section.js, sites/truckersnews.com/server/routes/content.js, sites/truckersnews.com/server/routes/home.js, sites/truckersnews.com/server/routes/website-section.js, sites/truckpartsandservice.com/server/routes/content.js, sites/truckpartsandservice.com/server/routes/home.js, sites/truckpartsandservice.com/server/routes/website-section.js
Move the newsletterState middleware to content, section & home routes.  In doing so I also update the newsletter pushdown menu logic to look at the local prop being set in the middleware for initiallyExpanded instead of just looking for the lack of cookie & lack of fromEmail.  The only reason hasCookie & fromEmail was set in the prop was to calculate initiallyExpanded.  So instead i just set initiallyExpanded in the prop instead of hasCookie & fromEmail.
=> Move newsletter middleware to specific sites and move setting of initiallyExpanded within middleware

packages/global/components/layouts/content/default.marko, packages/global/middleware/content-meter.js
This is a temp fix to update the conditions on when to display the overlay, apply different truncation & display the login/profile box on content pages.  Will put a second PR to clean up template and move conditional checks accordingly. 
Additional articles not matching the first three:
=> Temp fix for content meter gate

packages/global/scss/components/user.scss
=> Fix form css targeting when loading in content body

packages/global/config/identity-x-nav.js, packages/theme-monorail/components/site-menu/index.marko, packages/theme-monorail/scss/components/_site-menu.scss, sites/overdriveonline.com/config/navigation.js
- Add user links to Desktop & Mobile drop down menus.
- Update config to only display Sign Up vs Log In & Register.
- Update labels to Sign Up, Sign Out & Manage Account vs Log In, Register, My Account & Log Out
=> Add user links to drop down menu

packages/global/config/identity-x-nav.js, packages/theme-monorail/components/site-menu/index.marko, packages/theme-monorail/scss/components/_site-menu.scss
Display login link `Sign In` vs the register link to display in navigation.
=> Use login route vs register route when user logged-out

sites/truckersnews.com/server/styles/index.scss
Screenshot technically also includes pending changes from the Theme-Monorail Adjustments as well.
=> Change primary color on TN, improve visibility.

packages/global/components/blocks/content-meter.marko
PROD:
DEV:
(Dev includes changes made in: https://github.com/parameter1/base-cms/pull/329 but those are not required by this PR)
=> Add aria-labelled region to Content Meter.

sites/equipmentworld.com/server/templates/index.marko
=> Replace ‘Gear’ block with ‘Market Pulse’

packages/global/browser/dun-and-bradstreet.js
To prevent Olytics treating the value as delimited
=> Replace commas in D&B record values

packages/global/components/blocks/content-meter.marko, packages/global/middleware/content-meter.js, packages/global/middleware/newsletter-state.js, sites/truckpartsandservice.com/server/routes/content.js
add canBeInitiallyExpanded prop within newsletterState that the other middleware, specifically contentMeter, can also handle this condition.  In this case if can be initially expanded assume the newsletter push down, or content gating, will win and disable the contentMeter.  
First page visit:
Page refresh(second page visit and pushdown/cookie was already set):
=> Add canBeInitiallyExpanded checks to newsletterState & contentMeter middleware

packages/global/config/identity-x.js, packages/global/middleware/newsletter-state.js
This can only be required on the client side as it depends on the user picking US, Canada or Mexico as their countryCode for this field to display. If they choose anything else this field is no longer available to the user and can not be required server side.
=> Remove postalCode from list of serverRequiredFields

sites/overdriveonline.com/server/components/blocks/promo-card-rotation.marko
Shows in rotation with previous 2 promo cards:
=> Add whitepapers to promo cards

packages/global/config/omeda-identity-x.js, sites/ccjdigital.com/config/content-meter.js, sites/equipmentworld.com/config/content-meter.js, sites/hardworkingtrucks.com/config/content-meter.js, sites/overdriveonline.com/config/content-meter.js, sites/totallandscapecare.com/config/content-meter.js, sites/truckersnews.com/config/content-meter.js, sites/truckpartsandservice.com/config/content-meter.js
Add onLoginLinkSentFormatter that will check to see if the current user has the subscription to the current website product.  If it does assume the user has already been through this process and do not resubmit the promoCode for registration_meter, or reset the promoCode to undefined.  
Also add/ensure the promoCodes are set for the site not currently using the contentMeter.
**Example:**
First time visiting TPS.  I click a piece of content and fill in the content meter.  The payload is not modified as there is no omedaCustomerRecord yet.  so it send the email address and the promoCode as expected.  The user then has to click the link and file out their profile.  On authenticationSuccess the user is auto signed up to the daily.  
I then logout.  Come back and fill out the content meter …
=> Add onLoginLinkSentFormatter to adjust promoCode on the payload if user has website product

packages/global/config/omeda-identity-x.js, sites/ccjdigital.com/config/identity-x-opt-in-hooks.js, sites/equipmentworld.com/config/identity-x-opt-in-hooks.js, sites/overdriveonline.com/config/identity-x-opt-in-hooks.js, sites/truckpartsandservice.com/config/identity-x-opt-in-hooks.js
Add the `${pubCode} _profile_updated_meter` promoCode & corisponding demo onUserProfileUpdate step of registration.  Meaning if the given demo doesnt exists added it and set the promoCode.  At this point if the demo does exists do nothing, but I am guessing this will change.
=> Add onUserProfileUpdateFormatter for checking/setting of a profile demographics

packages/global/config/omeda-identity-x.js
When we are modifying the payload onAuthenticationSuccess ensure there are newSubscriptions with a array.length check
=> Ensure there are new subscriptions before modifying the payload onAuthenticationSucess

packages/global/components/layouts/content/default.marko
**Note the missing lazyloaded class in the left dev screen:**
=> Prevent lazy-loading of content body images

packages/global/components/layouts/content/default.marko
This will require the following PRs to be merged and deployed with a dep upgrade.
- https://github.com/parameter1/base-cms/pull/485
This will have to be merged and deployed for the new transcript field to appear in management 
- https://github.com/parameter1/base-platform/pull/183
This PR will:
- Add jumplink/anchor tag for transcript that sits below the embeded(this will only happen on videos)
- Add Transcript field a the bottom of content pages when present
=> Add new transcript field to default content layout

packages/global/scss/components/content-meter.scss
Update to correctly select the login link .form-group.  The fieldset selector is not there, but I updated it to select the form the .form-group.  This will fix the CLS that was happeing when the input and submit button where getting stacked.
=> Fix login form css targeting for content metter

packages/global/routes/static-page.js, packages/global/scss/core.scss, packages/global/templates/static/one-trust.marko, sites/equipmentworld.com/config/site.js, sites/hardworkingtrucks.com/config/site.js, sites/overdriveonline.com/config/site.js, sites/totallandscapecare.com/config/site.js, sites/truckersnews.com/config/site.js, sites/truckpartsandservice.com/config/site.js
convert the static page logic to support passing in multiple oneTrustIds and looping over them to create the target div and script includes.
=> Make oneTrust static pages support multiple div ids

packages/global/middleware/content-meter.js, packages/global/package.json, yarn.lock
Add a user agent check for user-agent having a browser.name === ‘Facebook’ to prevent the content meter from showing.
I test by setting the user agent to `'Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone9,1;FBMD/iPhone;FBSN/iOS;FBSV/14.1;FBSS/2;FBID/phone;FBLC/en_US;FBOP/5]',`  vs the standard `req.headers['user-agent']`
=> Prevents  content meter display when user agent's browser is Facebook

packages/global/browser/index.js
@requires https://github.com/parameter1/base-cms/pull/569 be merged and dep upgrade done. 
Add a event emitter for idenitty-x-created-new-user event with a payload of { useId, source }
**Created these variables, tags & triggers within GTM:** 
**Example results within GTM:**
=> Add identity-x-created-new-user event emitter

packages/global/components/document.marko
Find, format & vet the omeda oly_anon_id & oly_eny_id from cookies and send along to GTM as well as the idX id  when present.
=> Send oly_(eny/anon)_id to GTM

packages/global/components/blocks/sponsors.marko, packages/global/components/layouts/website-section/feed.marko
Screenshots showing what this looks like at various resolutions:
=> Display `global-sponsors-block` with respective sponsors of Trailblazer Award section page, TPS

packages/global/components/layouts/content/default.marko
Set the mobile-leaderboard-ad-name & mobile-leaderboard-ad-modifiers props according to the config.  This will also adjust and apply the modifiers for INLINE-LEADERBOARD-MOBILE template vs INLINE-CONTENT-MOBILE and apply the css accordingly.
=> Adjust ad injection body call with mobile ad property adjustments to fix CLS issue

packages/global/middleware/newsletter-state.js, sites/ccjdigital.com/config/newsletter.js, sites/equipmentworld.com/config/newsletter.js, sites/overdriveonline.com/config/newsletter.js, sites/truckpartsandservice.com/config/newsletter.js
Add isMobile check as well as adding the ability to configure the canBeInitiallyExpanded  value per site.
=> Adjust newsletterState to account for mobile and site level configuration

packages/global/middleware/newsletter-state.js, sites/ccjdigital.com/config/newsletter.js, sites/equipmentworld.com/config/newsletter.js, sites/overdriveonline.com/config/newsletter.js, sites/truckpartsandservice.com/config/newsletter.js
Adjust the newsletter middleware and config to be able to enable/disable the pushdown on mobile per site.
`newsletter.pushdown.disableMobileCBIE: true,`
=> Adjust newsletter pushdown with site level mobile config

sites/equipmentworld.com/server/templates/index.marko
These were missed in #552 and are causing a significantly elevated error rate on virgon graphql.
=> Update section aliases

packages/rigdig/scss/rigdig.scss, sites/truckhistoryreport.com/server/styles/index.scss, sites/truckhistoryreport.com/server/templates/index.marko
Update social label to be `Follow Overdrive`
Add small class to adjust font size on paragraphs under images
Fix h6 tags to prevent element wrapping:
=> Truck History Report adjustments to layout styles & social follow title 

packages/rigdig/browser/widget.vue
Update the error message to more user friendly version when you get errors from verify route:
<table>
<tr>
<th>
Invalid pin & 400 error directly from api
</th>
<th>
Report not found, but valid vin & we fire 404 error on /verify
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Update invalid & report not found error handling with widget

packages/payfabric/src/client.js, packages/rigdig/src/client.js
Now includes request/response headers and bodies, if debugging is enabled.
=> Add additional error logging to PF and RDBI apis

packages/rigdig/browser/checkout-modal.vue, packages/rigdig/package.json, packages/rigdig/src/index.js, packages/rigdig/src/send-error-notification.js, packages/rigdig/src/templates/error-notification.marko, sites/truckhistoryreport.com/server/templates/index.marko, yarn.lock
At the moment this is hard set to fail on line [64](https://github.com/parameter1/randall-reilly-websites/pull/614/files#diff-e22113b27008ca7a9283fd3a5e6bd6f8e439a8ce168179a9720c92dce38f19d2R64). remove added g As well as setting the to [here](https://github.com/parameter1/randall-reilly-websites/pull/614/files#diff-c3fbad4005d53604b844fe2fa90de9ac1ba15d7e0d5244e4ba0fa63e23c3236fR32) to support@rigdig.com instead of me. 
This will add retry ability as well as error notification when retry attempts fail.  
**New User facing error page:**
**New error notification:**
=> Update error handling on report generation portion of process

packages/rigdig/browser/checkout-header.vue
Trying to tighten up the form on step 2 remove top 2 paragraphs 
- We found a match for the VIN. To purchase the report, complete the payment process below.
- Reports are delivered instantly via email after payment.
=> Remove top copy on step 2 of process

sites/truckhistoryreport.com/server/styles/index.scss
This ensures it will sit ontop of the header and footer
=> Fix z-index when rigdig modal is present

sites/truckhistoryreport.com/config/navigation.js
This will prevent idx from injecting them into the menu.
routes will still work as expected.
=> Comment out user menu targets on Truck History Reports

packages/global/components/blocks/promos/ct-bev-survey-2.marko, packages/global/components/blocks/promos/ct-bev-survey.marko, packages/global/components/blocks/promos/marko.json, packages/global/scss/core.scss, sites/cleantrucking.com/server/components/blocks/marko.json, sites/cleantrucking.com/server/components/blocks/promo-card-rotation.marko, sites/cleantrucking.com/server/components/marko.json, sites/cleantrucking.com/server/templates/content/company.marko, sites/cleantrucking.com/server/templates/content/index.marko, sites/cleantrucking.com/server/templates/content/product.marko, sites/cleantrucking.com/server/templates/index.marko, sites/cleantrucking.com/server/templates/website-section/index.marko
Add two promo cards to display survey reports for CT home page as well as bottom of all other pages.
=> Add survey card promo block to CT hompage

packages/rigdig/scss/rigdig.scss
These __bg-wrapper already have negative margins left/right to pull them out to the edge of the page.  This prevents anything from falling off the page, also preventing a left right scroll bar.
Production:
Dev:
=> Prevent overflow from causing scroll on mobile

sites/cleantrucking.com/server/styles/index.scss
Remove 700px max width on Survey Report content landing page.  At the moment this is id specific.  If this increases we will look at making this label/config based.
=> Add simple css to widen survey page

packages/global/components/blocks/promos/bev-survey-image-only.marko, packages/global/components/blocks/promos/bev-survey-text-only.marko, packages/global/components/blocks/promos/bev-survey.marko, packages/global/components/blocks/promos/marko.json, packages/global/scss/components/blocks/_promo-cards.scss, packages/global/scss/core.scss, sites/cleantrucking.com/server/components/blocks/promo-card-rotation.marko, sites/cleantrucking.com/server/templates/content/company.marko, sites/cleantrucking.com/server/templates/content/index.marko, sites/cleantrucking.com/server/templates/content/product.marko, sites/cleantrucking.com/server/templates/index.marko, sites/cleantrucking.com/server/templates/website-section/index.marko
Update block names and calls to display image only and then text only version of the bev survey promo cards.  These wil display at the bottom of section and content pages.
=> Update ct survey promo calls

packages/global/components/layouts/content/default.marko, packages/global/package.json, packages/global/scss/components/blocks/_thr-vin-lookup-inbody-promo-card.scss, packages/global/scss/core.scss, packages/rigdig/browser/widget.vue, packages/rigdig/components/widget.marko
Add the ability to use shared THR widget on the THR homepage right rail as well as being used/configured for use with the OVD content body.
=> Update THR widget with the ability to be called within content body

sites/overdriveonline.com/server/components/blocks/promo-card-rotation.marko
Add logic to dynamically include the THR promo card to the homepage bottom left card, based on inbody promo display being enabled or disabled.
=> Conditionally show/add THR promo card based on in-body promo display

packages/global/components/layouts/content/default.marko, packages/rigdig/browser/widget.vue, packages/rigdig/components/widget.marko
This will fix the blurry images and correctly utilizes the lazy load and data-src, data-srcset functionality built into the site.  I also update the image calls to SVG, once I figure out how to export them correctly from FIGMA.
This also allow for the pass through of placeholder within the marko component wrapper.
=> Fix THR promo images & adjust marko component prop pass through

sites/ccjdigital.com/server/templates/index.marko, sites/equipmentworld.com/server/components/blocks/marko.json, sites/equipmentworld.com/server/components/blocks/promo-card-rotation.marko, sites/equipmentworld.com/server/components/marko.json, sites/equipmentworld.com/server/templates/index.marko, sites/overdriveonline.com/server/components/blocks/promo-card-rotation.marko, sites/overdriveonline.com/server/templates/index.marko, sites/totallandscapecare.com/marko.json, sites/totallandscapecare.com/server/components/blocks/marko.json, sites/totallandscapecare.com/server/components/blocks/promo-card-rotation.marko, sites/totallandscapecare.com/server/components/marko.json, sites/totallandscapecare.com/server/templates/index.marko, sites/truckpartsandservice.com/server/components/blocks/marko.json, sites/truckpartsandservice.com/server/components/blocks/promo-card-rotation.marko, sites/truckpartsandservice.com/server/components/marko.json, sites/truckpartsandservice.com/server/templates/index.marko
Add the ability to push the Partner Insights call into the promo card rotation based on a env config(SHOW_PARTNER_INSIGHTS_AS_PROMO) set to true.  
Support this:
- CCJ (no NativeX)
- EQW
- OVD ( no nativeX or whitepaper currently running????????)
- TLC (no NativeX)
- TPS (no NativeX)
Does not support:
- CT
- HWT
- TN
- THR
=> Add Partner Insight env config support for merging  standalone block into promo card rotation

packages/global/components/layouts/content/default.marko, packages/rigdig/components/widget.marko
=> Update source prop  to be widget vs landing page on OVD's in body history report widget. 

packages/global/components/blocks/sponsors.marko, sites/truckpartsandservice.com/server/templates/static/distributor-of-the-year-award.marko
Notable changes include the additional of website links for the sponsors, changing heading colors to the appropriate blue and adjusting the styling of the past winners table.
=> DOTY Information Page Corrections

packages/payfabric/src/index.js, packages/payfabric/src/utils/calculate-sales-tax.js, packages/rigdig/browser/checkout-modal.vue, packages/rigdig/browser/widget.vue, packages/rigdig/components/widget.marko, packages/rigdig/scss/rigdig.scss
Previously this was using: https://developer.avalara.com/api-reference/avatax/rest/v2/methods/TaxContent/TaxRatesByPostalCode/ which only supported US postal codes, this now however will use https://developer.avalara.com/api-reference/avatax/rest/v2/methods/Transactions/CreateTransaction/ which will support "all" (not all of which have been tested) valid postal codes.
Using `L8G 2V1` (Ontario, Canada):
Using `53188` (Waukesha, Wisconsin):
Using Mexico as the country
=> Correct transaction amount truncation and support all postal codes

packages/global/components/content-query-with-injected-native-ads.marko, packages/global/components/layouts/website-section/feed.marko, packages/global/components/marko.json
RETURNED:
NOT RETURNED:
This functions as it does on other sites.
=> Scooch in Native-X ad when returned

sites/truckhistoryreport.com/server/templates/index.marko
=> Remove ‘Welcome’ box on Truck History Report

sites/ccjdigital.com/server/templates/index.marko
=> Add ‘View More’ link to Partner Insights block on homepage

packages/global/browser/load-analyzer.vue
This will allow for people not to have to enter a value & also set it to 0 as to not effect the formula.
=> Adjust deadhead to have a default of 0 as well as allow for 0 as a valid input

packages/global/components/blocks/job-search.marko, packages/global/components/layouts/content/default.marko
Update display logic of when/how jobs box show display
- Always show when user is present
- If there is no user randomize display between signup & job search
- remove restriction on jobs content
=> Update jobs search box inputs & inline display logic

packages/global/components/document.marko, sites/truckersnews.com/config/gam.js
Set to false on TN only and to true by default
At the moment oneTrust  is being paused within their GTM container.  This is why the initi only true was implemented.  To allow for one trust to set specifics and then trigger the init of ads.  This has been broken with the pausing of the gtm tag.
=> Add ability to set gam initOnly on a site level

packages/global/scss/components/blocks/_load-analyzer-inbody.scss
=> Fix section name style & marginBottom on inBody ad
